[package]
name = "rust-testing"
version = "0.2.19"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
futures-util = "0.3.31"
log = "0.4.22"
serde = "1.0.216"
serde_json = "1.0.134"
