name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        with:
          github-token: ${{ github.token }}
          skip-commit: true
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          skip-git-pull: true
          output-file: false
          create-summary: true
          version-file: .github/package.yml

  release:
    name: Release
    needs: changelog
    if: needs.changelog.outputs.skipped == 'false'
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows
            os: windows-latest
          - host: linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Get the latest tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Latest tag: $TAG"

      - name: Build release binary
        run: |
          cargo build -r

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          tag_name: ${{ env.TAG }}
          prerelease: false
          draft: false
          files: ${{ matrix.os == 'windows-latest' && 'target/release/rust-testing.exe' || 'target/release/rust-testing' }}
          generate_release_notes: true
          name: ${{ env.TAG }}
          body: |
            <details>
              ${{ needs.changelog.outputs.clean_changelog }}
            </details>
