name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows
            os: windows-latest
          - host: linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build release binary
        run: |
          cargo build -r

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          tag_name: ${{ github.ref_name }}
          files: ${{ matrix.os == 'windows-latest' && 'target/release/rust-testing.exe' || 'target/release/rust-testing' }}
          generate_release_notes: true
          name: ${{ github.ref_name }}
